import { CampaignType } from "../data/campaign-types";
import { CampaignConfig } from "../store/campaign-store";
import { PodRow } from "../calc/staffing";
import { SprintBreakdown } from "../calc/sprint";
import { PricingResult, VendorLine, outcomeTargetFor } from "../calc/pricing";
import { Freelancer } from "../store/admin-store";
import { fmtMoney, fmtInr } from "../utils";

function esc(value: string | number): string {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

const DOC_STYLES = `
  body{font-family:'IBM Plex Sans',Arial,sans-serif;background:#faf8f3;color:#1b2129;margin:0;padding:0;font-size:14px;line-height:1.55}
  .wrap{max-width:820px;margin:0 auto;padding:36px 28px 60px}
  h1{font-family:'Space Grotesk',sans-serif;font-size:26px;font-weight:600;margin:0 0 4px}
  h2{font-family:'Space Grotesk',sans-serif;font-size:16px;font-weight:600;margin:28px 0 10px;padding-bottom:6px;border-bottom:1px solid #e6e0d2}
  .eyebrow{font-family:'IBM Plex Mono',monospace;font-size:10px;letter-spacing:.1em;text-transform:uppercase;color:#e9941a;margin-bottom:6px}
  .meta{color:#6a7280;font-size:12.5px;margin-bottom:18px}
  table{width:100%;border-collapse:collapse;font-size:13px;margin-bottom:6px}
  td,th{padding:7px 8px;border-bottom:1px solid #e6e0d2;text-align:left;vertical-align:top}
  th{font-family:'IBM Plex Mono',monospace;font-size:10px;text-transform:uppercase;letter-spacing:.05em;color:#6a7280}
  .num{text-align:right;font-family:'IBM Plex Mono',monospace}
  .card{background:#fff;border:1px solid #e6e0d2;border-radius:4px;padding:14px 16px;margin-bottom:10px}
  .tag{display:inline-block;font-family:'IBM Plex Mono',monospace;font-size:9.5px;padding:2px 7px;border-radius:2px;background:#f0ecdf;color:#8a8578;margin:2px 3px 0 0}
  .total-row td{font-weight:600;font-size:15px;border-top:2px solid #e9941a;border-bottom:none}
  .note{font-size:11.5px;color:#6a7280;margin-top:4px}
  .deliverable{margin-top:6px;border-left:2px solid #e9941a;background:#f0ecdf;padding:6px 10px;font-size:12px;color:#4a4a44}
  footer{margin-top:36px;padding-top:14px;border-top:1px solid #e6e0d2;font-size:11.5px;color:#6a7280}
  .bidgrid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:10px}
  .bidfield{border-bottom:1px solid #1b2129;min-height:22px;padding:2px 0}
  .bidlabel{font-family:'IBM Plex Mono',monospace;font-size:9px;text-transform:uppercase;letter-spacing:.05em;color:#6a7280;margin-bottom:2px}
  .status-open{color:#4d9685;font-weight:600}
  .status-assigned{color:#e9941a;font-weight:600}
`;

function documentShell(title: string, body: string): string {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>${esc(title)}</title>
<style>${DOC_STYLES}</style>
</head>
<body>
<div class="wrap">
${body}
<footer>Generated by ClarityHQ Campaign Marketplace — an internal discussion demo. Not a binding document.</footer>
</div>
</body>
</html>`;
}

function briefSectionsHtml(ct: CampaignType, config: CampaignConfig): string {
  return `
<h2>Campaign Overview</h2>
<div class="card">
  <table>
    <tr><td>Client</td><td>${esc(config.client || "—")}</td></tr>
    <tr><td>Campaign type</td><td>${esc(ct.label)}</td></tr>
    <tr><td>Objective</td><td>${esc(config.objective)}</td></tr>
    <tr><td>Selling</td><td>${esc(config.sell || "—")}</td></tr>
    <tr><td>Goal</td><td>${esc(config.goal || "—")}</td></tr>
  </table>
</div>

<h2>Audience &amp; Targeting</h2>
<div class="card">
  <table>
    <tr><td>Industry</td><td>${esc(config.industry)}</td></tr>
    <tr><td>${ct.mode === "sales" ? "Contact list size" : "Target audience size"}</td><td>${esc(config.audienceSize.toLocaleString())}</td></tr>
    ${ct.mode === "sales" ? `<tr><td>ICP</td><td>${esc(config.icp || "—")}</td></tr><tr><td>Source</td><td>${esc(config.source)}</td></tr>` : ""}
  </table>
</div>

<h2>Channels &amp; Assets</h2>
<div class="card">
  <div>${config.channels.map((c) => `<span class="tag">${esc(c)}</span>`).join("")}</div>
  ${
    config.assets.length > 0
      ? `<table style="margin-top:10px"><tr><th>Asset</th><th>Qty</th><th>Rate</th><th>Note</th></tr>${config.assets
          .map((a) => `<tr><td>${esc(a.type)}</td><td>${esc(a.qty)}</td><td class="num">${fmtMoney(a.rate)}</td><td style="font-size:11.5px;color:#6a7280">${esc(a.note ?? "")}</td></tr>`)
          .join("")}</table>`
      : `<p class="note">No deliverable assets added.</p>`
  }
</div>

<h2>Funnel &amp; Commercial</h2>
<div class="card">
  <table>
    <tr><td>Qualified %</td><td class="num">${config.qualifiedPct}%</td></tr>
    <tr><td>Opportunity %</td><td class="num">${config.opportunityPct}%</td></tr>
    <tr><td>Close %</td><td class="num">${config.closePct}%</td></tr>
    <tr><td>ASP / Deal value</td><td class="num">${fmtMoney(config.asp)}</td></tr>
    <tr><td>Ad spend</td><td class="num">${fmtMoney(config.adSpend)} (${esc(config.adSpendCadence)})</td></tr>
  </table>
</div>

<h2>Delivery</h2>
<div class="card">
  <table>
    <tr><td>Owner</td><td>${esc(config.owner || "—")}</td></tr>
    <tr><td>Weeks</td><td>${config.weeks}</td></tr>
    <tr><td>Sprints</td><td>${config.sprints}</td></tr>
  </table>
  ${config.notes ? `<p class="note"><strong>Notes:</strong> ${esc(config.notes)}</p>` : ""}
  ${config.risks ? `<p class="note"><strong>Risks / dependencies:</strong> ${esc(config.risks)}</p>` : ""}
</div>`;
}

function podHtml(pod: PodRow[]): string {
  return `
<h2>Pod</h2>
${pod
  .map(
    (row) => `<div class="card">
  <table><tr><td style="width:26px">${row.stepNumber}</td><td><strong>${esc(row.stepTitle)}</strong></td><td class="num">${esc(row.role)} · ${row.hours} hrs @ ${fmtMoney(row.rate)}/hr = ${fmtMoney(row.hours * row.rate)}</td></tr></table>
  <div class="deliverable">${esc(row.out)}</div>
</div>`
  )
  .join("")}`;
}

function timelineHtml(bd: SprintBreakdown): string {
  return `
<h2>Timeline</h2>
<p class="meta">${bd.totalDays} elapsed days · ~${bd.approxWeeks} weeks · ${bd.sprints.length} sprints</p>
${bd.sprints
  .map(
    (sp) => `<div class="card">
  <strong>Sprint ${sp.n}</strong> <span class="note">(${sp.days} days)</span>
  <table style="margin-top:6px">${sp.rows
    .map((r) => `<tr><td style="width:90px">${esc(r.rangeLabel)}</td><td>${esc(r.stepTitle)}</td><td class="num">${esc(r.role)}</td></tr>`)
    .join("")}</table>
</div>`
  )
  .join("")}`;
}

function vendorLinesHtml(vendorLines: VendorLine[]): string {
  if (vendorLines.length === 0) return "";
  const usd = vendorLines.filter((v) => v.currency === "USD");
  const inr = vendorLines.filter((v) => v.currency === "INR");
  return `
<h2>Vendor &amp; Specialist Capacity</h2>
<div class="card">
  ${usd.length > 0 ? `<p><strong>Vendors:</strong> ${usd.map((v) => `${esc(v.name)} (${fmtMoney(v.cost)})`).join(", ")}</p>` : ""}
  ${inr.length > 0 ? `<p><strong>Specialist capacity:</strong> ${inr.map((v) => `${esc(v.name)} (${fmtInr(v.cost)})`).join(", ")}</p>` : ""}
</div>`;
}

export function buildBriefHtml(
  ct: CampaignType,
  config: CampaignConfig,
  pod: PodRow[],
  sprintBreakdown: SprintBreakdown | null,
  vendorLines: VendorLine[] = []
): string {
  const title = `${config.name || "Untitled campaign"} — Campaign Brief`;
  const body = `
<div class="eyebrow">Campaign Brief</div>
<h1>${esc(config.client || "Client")} — ${esc(config.name || "Untitled campaign")}</h1>
<p class="meta">${esc(ct.label)} · Generated ${new Date().toLocaleDateString()}</p>
${briefSectionsHtml(ct, config)}
${podHtml(pod)}
${vendorLinesHtml(vendorLines)}
${sprintBreakdown ? timelineHtml(sprintBreakdown) : ""}`;
  return documentShell(title, body);
}

export function buildProposalHtml(
  ct: CampaignType,
  config: CampaignConfig,
  pod: PodRow[],
  sprintBreakdown: SprintBreakdown | null,
  pricing: PricingResult,
  vendorLines: VendorLine[]
): string {
  const title = `${config.name || "Untitled campaign"} — Proposal`;
  const outcomeTarget = outcomeTargetFor(config.outcomeMetric, {
    audienceSize: config.audienceSize,
    qualifiedPct: config.qualifiedPct,
    opportunityPct: config.opportunityPct,
    closePct: config.closePct,
    asp: config.asp,
  });
  const metricLabel =
    config.outcomeMetric === "custom" ? config.outcomeCustomLabel || "custom outcome" : config.outcomeMetric;

  const usdVendorLines = vendorLines.filter((v) => v.currency === "USD");
  const inrVendorLines = vendorLines.filter((v) => v.currency === "INR");

  const body = `
<div class="eyebrow">Proposal</div>
<h1>${esc(config.client || "Client")} — ${esc(config.name || "Untitled campaign")}</h1>
<p class="meta">${esc(ct.label)} · Generated ${new Date().toLocaleDateString()}</p>

<h2>What we&apos;re proposing</h2>
<div class="card">
  <p>${esc(ct.desc)}</p>
  <p class="note">${esc(config.goal || "")}</p>
</div>

${briefSectionsHtml(ct, config)}
${podHtml(pod)}
${sprintBreakdown ? timelineHtml(sprintBreakdown) : ""}

<h2>Pricing</h2>
<div class="card">
  <table>
    <tr><td>Total cost (pod + assets + tech)</td><td class="num">${fmtMoney(pricing.totalCost)}</td></tr>
    ${
      config.priceMode === "fixed"
        ? `<tr><td>Cost × 4</td><td class="num">${fmtMoney(pricing.fixedComponent)}</td></tr>`
        : `<tr><td>Cost × 3 (fixed component)</td><td class="num">${fmtMoney(pricing.fixedComponent)}</td></tr>
           <tr><td>Variable at target (${outcomeTarget} × ${fmtMoney(config.outcomeRate)}/${esc(metricLabel)})</td><td class="num">${fmtMoney(pricing.baselineVariable)}</td></tr>`
    }
    <tr class="total-row"><td>Client price (${esc(config.priceMode)})</td><td class="num">${fmtMoney(pricing.totalPrice)}</td></tr>
    <tr><td>Ad spend (${esc(config.adSpendCadence)}, at-cost, separate)</td><td class="num">${fmtMoney(pricing.adSpend)}</td></tr>
    <tr><td>Vendor costs (at-cost, separate)</td><td class="num">${fmtMoney(pricing.vendorCostUsd)}</td></tr>
    ${pricing.specialistCostInr > 0 ? `<tr><td>Specialist retainer capacity (at-cost, separate)</td><td class="num">${fmtInr(pricing.specialistCostInr)}</td></tr>` : ""}
    <tr class="total-row"><td>Grand total (USD)</td><td class="num">${fmtMoney(pricing.grandTotal)}</td></tr>
  </table>
  ${
    config.priceMode === "hybrid"
      ? `<p class="note">Variable component invoiced on completion, based on ${esc(metricLabel)} achieved.</p>`
      : ""
  }
  ${
    usdVendorLines.length > 0
      ? `<p class="note"><strong>Vendors included:</strong> ${usdVendorLines.map((v) => `${esc(v.name)} (${fmtMoney(v.cost)})`).join(", ")}</p>`
      : ""
  }
  ${
    inrVendorLines.length > 0
      ? `<p class="note"><strong>Specialist capacity included:</strong> ${inrVendorLines.map((v) => `${esc(v.name)} (${fmtInr(v.cost)})`).join(", ")}</p>`
      : ""
  }
</div>

<h2>Payment</h2>
<div class="card">
  <p>100% of the fixed / base component, ad spend, and vendor costs is due on approval.</p>
  ${
    config.priceMode === "hybrid"
      ? `<p class="note">Variable component invoiced on completion, based on ${esc(metricLabel)} achieved.</p>`
      : ""
  }
</div>`;
  return documentShell(title, body);
}

function stepTimelineLookup(bd: SprintBreakdown | null): Map<string, { sprintN: number; rangeLabel: string }> {
  const map = new Map<string, { sprintN: number; rangeLabel: string }>();
  if (!bd) return map;
  for (const sprint of bd.sprints) {
    for (const row of sprint.rows) {
      map.set(row.stepTitle, { sprintN: sprint.n, rangeLabel: row.rangeLabel });
    }
  }
  return map;
}

// A neutral, freelancer-facing doc listing every pod role's scope, indicative
// rate, and timeline window, with blank fields for a bid, availability, and an
// intent-to-work confirmation — meant to be circulated for open bidding.
export function buildFreelancerCallHtml(
  ct: CampaignType,
  config: CampaignConfig,
  pod: PodRow[],
  sprintBreakdown: SprintBreakdown | null,
  freelancers: Freelancer[],
  podAssignments: Record<number, string>
): string {
  const title = `${config.name || "Untitled campaign"} — Freelancer Call for Bids`;
  const timelineLookup = stepTimelineLookup(sprintBreakdown);

  const body = `
<div class="eyebrow">Call for Bids — Freelancer Scope of Work</div>
<h1>${esc(config.name || "Untitled campaign")}</h1>
<p class="meta">${esc(ct.label)} · ${esc(config.client || "Client withheld pending assignment")} · Generated ${new Date().toLocaleDateString()}</p>

<div class="card">
  <p>We&apos;re staffing the roles below for this campaign. Review the scope and deliverable for any role
  you&apos;re interested in, then submit your proposed rate, availability, and confirm your intent to work
  using the fields provided.</p>
  <p class="note">Timeline: ${sprintBreakdown ? `${sprintBreakdown.totalDays} elapsed days · ~${sprintBreakdown.approxWeeks} weeks · ${sprintBreakdown.sprints.length} sprints` : "TBD"} · Channels: ${config.channels.join(", ")}</p>
</div>

${pod
  .map((row) => {
    const assignedId = podAssignments[row.stepNumber];
    const assignedFreelancer = freelancers.find((f) => f.id === assignedId);
    const timing = timelineLookup.get(row.stepTitle);
    return `<div class="card">
  <table><tr>
    <td style="width:26px">${row.stepNumber}</td>
    <td><strong>${esc(row.stepTitle)}</strong><br><span class="note">${esc(row.role)}</span></td>
    <td class="num">
      ${row.hours} hrs indicative<br>
      ${fmtMoney(row.rate)}/hr indicative<br>
      ${timing ? `Sprint ${timing.sprintN} · ${esc(timing.rangeLabel)}` : ""}
    </td>
  </tr></table>
  <div class="deliverable">${esc(row.out)}</div>
  <p class="note" style="margin-top:8px">
    Status: ${assignedFreelancer ? `<span class="status-assigned">Provisionally assigned — ${esc(assignedFreelancer.name)}</span>` : `<span class="status-open">Open — accepting bids</span>`}
  </p>
  <div class="bidgrid">
    <div><div class="bidlabel">Your name</div><div class="bidfield"></div></div>
    <div><div class="bidlabel">Proposed rate ($/hr or fixed)</div><div class="bidfield"></div></div>
    <div><div class="bidlabel">Availability / start date</div><div class="bidfield"></div></div>
    <div><div class="bidlabel">Intent to work (sign / date)</div><div class="bidfield"></div></div>
  </div>
</div>`;
  })
  .join("")}`;
  return documentShell(title, body);
}

export function downloadHtmlFile(filename: string, html: string): void {
  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
